import React, { useEffect, useState } from 'react';
import { useSpotifyToken } from './hooks/useSpotifyToken';
import { usePipeline } from './hooks/usePipeline';
import { LoginScreen } from './components/LoginScreen';
import { LoadingScreen } from './components/LoadingScreen';
import { RecommendationGrid } from './components/RecommendationGrid';
import { ErrorBanner } from './components/ErrorBanner';
import { InstantFavorites } from './components/InstantFavorites';
import { CustomArtistSelector } from './components/CustomArtistSelector';
import { getTopTracks, getRecentlyPlayed, getCurrentUserId, createPlaylist, addTracksToPlaylist, getUserPlaylists, replacePlaylistTracks } from './api/spotify';
import { useRateLimitCooldown } from './hooks/useRateLimitCooldown';

function App() {
  const { token, tokenRef, loading: tokenLoading, error: tokenError, login, logout } = useSpotifyToken();
  const { run, abort, step, progress, recommendations, seedArtists, error: pipelineError, warnings, logs, PIPELINE_STEPS } = usePipeline(tokenRef);
  const cooldown = useRateLimitCooldown();
  const [timeRange, setTimeRange] = useState('medium_term');
  const [mode, setMode] = useState('auto'); // 'auto' or 'custom'
  const [customArtists, setCustomArtists] = useState([]);
  const [localWarnings, setLocalWarnings] = useState([]);
  const [instantTracks, setInstantTracks] = useState([]);
  const [instantLoading, setInstantLoading] = useState(false);
  const [exportedPlaylistId, setExportedPlaylistId] = useState(null);
  const [isExporting, setIsExporting] = useState(false);

  const handleAddCustomArtist = (artist) => {
    setCustomArtists(prev => {
      if (prev.some(a => a.id === artist.id) || prev.length >= 5) return prev;
      return [...prev, artist];
    });
  };

  const handleRemoveCustomArtist = (id) => {
    setCustomArtists(prev => prev.filter(a => a.id !== id));
  };

  // Reset playlist state on new run
  useEffect(() => {
    setExportedPlaylistId(null);
  }, [recommendations, timeRange]);

  // Auto-sync to playlist when recommendations are generated
  useEffect(() => {
    if (recommendations && recommendations.length > 0 && !exportedPlaylistId && !isExporting) {
      handleExportPlaylist();
    }
  }, [recommendations]);

  // Auto-run pipeline when token is obtained or when timeRange changes (Auto Mode only)
  useEffect(() => {
    if (token && mode === 'auto') {
      run(timeRange);
    }
    return () => {
      abort();
    };
  }, [token, timeRange, mode, run, abort]);

  // Load instant heavy rotation favorites (staggered by 1000ms to prevent startup API spikes)
  useEffect(() => {
    if (!token) return;

    setInstantLoading(true);
    const timer = setTimeout(() => {
      Promise.allSettled([
        getTopTracks(tokenRef, 15),
        getRecentlyPlayed(tokenRef, 15)
      ]).then(([topRes, recentRes]) => {
        const tops = topRes.status === 'fulfilled' ? topRes.value : [];
        const recents = recentRes.status === 'fulfilled' ? recentRes.value : [];
        
        // Merge and deduplicate by track ID
        const merged = new Map();
        tops.forEach(t => t?.id && merged.set(t.id, t));
        recents.forEach(t => t?.id && !merged.has(t.id) && merged.set(t.id, t));
        
        setInstantTracks([...merged.values()].slice(0, 10));
        setInstantLoading(false);
      });
    }, 1000);

    return () => clearTimeout(timer);
  }, [token, tokenRef]);

  // Sync warnings state
  useEffect(() => {
    setLocalWarnings(warnings);
  }, [warnings]);

  const handleDismissWarning = (warnToDismiss) => {
    setLocalWarnings(prev => prev.filter(w => w !== warnToDismiss));
  };

  const handleExportPlaylist = async () => {
    if (!token || !recommendations.length) return;
    setIsExporting(true);
    if (tokenRef.onLog) {
      tokenRef.onLog('Initializing Spotify playlist synchronization...');
    }
    try {
      const userId = await getCurrentUserId(tokenRef);
      if (!userId) {
        throw new Error('Could not fetch Spotify user ID.');
      }
      
      if (tokenRef.onLog) {
        tokenRef.onLog('Searching for existing "My Co-Listening Mix" playlist...');
      }
      
      const playlists = await getUserPlaylists(tokenRef);
      let playlist = playlists.find(p => p.name === 'My Co-Listening Mix' && p.owner?.id === userId);
      
      const trackUris = recommendations.map(t => t.uri).filter(Boolean);
      
      const artistNamesStr = seedArtists.map(a => a.name).join(', ');
      const playlistDesc = artistNamesStr 
        ? `A personalized co-listening recommendations mix blending ${artistNamesStr}. Generated by Spotify Recommender.`
        : `Your custom co-listening recommendations mix, updated on ${new Date().toLocaleDateString()}.`;

      if (playlist) {
        if (tokenRef.onLog) {
          tokenRef.onLog(`Found existing "My Co-Listening Mix" playlist (ID: ${playlist.id}). Replacing tracks...`);
        }
        const res = await replacePlaylistTracks(playlist.id, trackUris, tokenRef);
        if (!res) {
          throw new Error('Failed to replace tracks in existing Spotify playlist.');
        }
        if (tokenRef.onLog) {
          tokenRef.onLog(`[Success] Playlist successfully synchronized! ID: ${playlist.id}`);
          tokenRef.onLog(`[Success] Direct Link: https://open.spotify.com/playlist/${playlist.id}`);
        }
      } else {
        if (tokenRef.onLog) {
          tokenRef.onLog('Creating new "My Co-Listening Mix" playlist...');
        }
        const newPlaylist = await createPlaylist(userId, 'My Co-Listening Mix', playlistDesc, tokenRef);
        if (!newPlaylist || !newPlaylist.id) {
          throw new Error('Failed to create Spotify playlist.');
        }
        const res = await addTracksToPlaylist(newPlaylist.id, trackUris, tokenRef);
        if (!res) {
          throw new Error('Failed to add tracks to the newly created Spotify playlist.');
        }
        playlist = newPlaylist;
        if (tokenRef.onLog) {
          tokenRef.onLog(`[Success] Playlist successfully created & populated! ID: ${playlist.id}`);
          tokenRef.onLog(`[Success] Direct Link: https://open.spotify.com/playlist/${playlist.id}`);
        }
      }
      
      setExportedPlaylistId(playlist.id);
    } catch (err) {
      console.error('Failed to sync playlist:', err);
      if (tokenRef.onLog) {
        tokenRef.onLog(`[Error] Failed to synchronize playlist: ${err.message || err}`);
      }
    } finally {
      setIsExporting(false);
    }
  };

  const handleRetry = () => {
    run(timeRange, mode === 'custom' ? customArtists : null);
  };

  const handleChangeTimeRange = (newRange) => {
    setTimeRange(newRange);
  };

  const handleOpenTimeRangeSelect = () => {
    setTimeRange(prev => {
      const nextMap = {
        'medium_term': 'long_term',
        'long_term': 'short_term',
        'short_term': 'medium_term'
      };
      return nextMap[prev] ?? 'medium_term';
    });
  };

  if (tokenLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-[#121212] text-gray-200">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin"></div>
          <p className="text-xs uppercase tracking-widest text-neutral-400 font-semibold font-mono animate-pulse">
            Establishing Secure Link...
          </p>
        </div>
      </div>
    );
  }

  if (!token) {
    return (
      <div className="min-h-screen bg-[#121212] text-gray-200 py-12">
        <LoginScreen onLogin={login} error={tokenError} />
      </div>
    );
  }

  const isPipelineRunning = step >= 0;

  return (
    <div className="min-h-screen bg-[#121212] text-gray-200 flex flex-col">
      {/* Header Bar */}
      <header className="sticky top-0 z-50 bg-[#121212]/80 backdrop-blur-md border-b border-neutral-900 py-4 px-6 md:px-12 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xl font-bold text-white tracking-tight flex items-center gap-1.5">
            <span className="text-emerald-500">♫</span> Spotify Recommender
          </span>
        </div>
        <div className="flex items-center gap-4">
          <button
            onClick={logout}
            className="px-4 py-2 text-xs font-semibold rounded-full border border-neutral-800 hover:border-neutral-700 bg-neutral-900 hover:bg-neutral-850 text-neutral-300 hover:text-white transition-all cursor-pointer"
            aria-label="Log out of Spotify"
          >
            Log Out
          </button>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 md:px-8 py-8 flex flex-col justify-start">
        
        {/* Error Banner */}
        {pipelineError && (
          <ErrorBanner
            error={pipelineError}
            onRetry={handleRetry}
            onChangeTimeRange={handleOpenTimeRangeSelect}
            onLogout={logout}
            cooldown={cooldown}
          />
        )}

        {/* Dashboard Responsive Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start w-full">
          {/* Main Content (Left: 8 columns) */}
          <div className="lg:col-span-8 space-y-6 w-full">
            {isPipelineRunning ? (
              <div className="bg-neutral-950/20 border border-neutral-900/80 rounded-2xl p-6 shadow-xl space-y-4">
                <LoadingScreen step={step} progress={progress} steps={PIPELINE_STEPS} logs={logs} />
                <div className="flex justify-center mt-2">
                  <button
                    onClick={abort}
                    className="px-4 py-2 text-xs font-semibold rounded-full border border-red-900/30 hover:border-red-900 bg-red-950/20 hover:bg-red-950/40 text-red-400 transition-all cursor-pointer"
                    aria-label="Cancel recommendation engine"
                  >
                    Cancel Analysis
                  </button>
                </div>
              </div>
            ) : recommendations && recommendations.length > 0 ? (
              <div className="space-y-6 animate-fadeIn w-full">
                <div className="space-y-1.5">
                  <h2 className="text-2xl font-extrabold text-white tracking-tight">Your Custom Playlist</h2>
                  <p className="text-sm text-neutral-400">
                    Fresh, unheard co-listening recommendations based on your unique profile.
                  </p>
                </div>
                
                <RecommendationGrid
                  recommendations={recommendations}
                  warnings={localWarnings}
                  onDismissWarning={handleDismissWarning}
                  timeRange={timeRange}
                  onChangeTimeRange={handleChangeTimeRange}
                  isPipelineRunning={isPipelineRunning}
                  onRefresh={handleRetry}
                  exportedPlaylistId={exportedPlaylistId}
                  isExporting={isExporting}
                  onExportPlaylist={handleExportPlaylist}
                />
              </div>
            ) : (
              !pipelineError && (
                <div className="w-full bg-neutral-900/40 border border-neutral-800/80 backdrop-blur-xl rounded-3xl p-6 md:p-8 shadow-2xl space-y-8 relative overflow-hidden transition-all duration-300 hover:border-neutral-700/80 text-left">
                  
                  {/* Mode Tabs */}
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold text-white tracking-tight">Curate Your Seed Profile</h3>
                    <p className="text-xs text-neutral-400">Select how we should extract your musical preferences for the analysis.</p>
                    
                    <div className="inline-flex rounded-xl p-1 bg-neutral-950 border border-neutral-850 mt-2" role="group">
                      <button
                        onClick={() => setMode('auto')}
                        className={`px-4 py-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                          mode === 'auto'
                            ? 'bg-emerald-500 text-neutral-950 shadow'
                            : 'text-neutral-400 hover:text-white'
                        }`}
                      >
                        Auto Profile (Top Artists)
                      </button>
                      <button
                        onClick={() => setMode('custom')}
                        className={`px-4 py-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                          mode === 'custom'
                            ? 'bg-emerald-500 text-neutral-950 shadow'
                            : 'text-neutral-400 hover:text-white'
                        }`}
                      >
                        Custom Blend (Select Artists)
                      </button>
                    </div>
                  </div>

                  {/* Mode Render */}
                  {mode === 'auto' ? (
                    <div className="p-5 rounded-2xl bg-neutral-950/40 border border-neutral-800/60 flex items-start gap-4 animate-fadeIn">
                      <span className="text-2xl text-emerald-400 shrink-0 select-none">🎛</span>
                      <div className="space-y-1">
                        <h4 className="text-xs font-bold text-white uppercase tracking-widest font-mono">Listening History Profile</h4>
                        <p className="text-xs text-neutral-400 leading-relaxed">
                          We will scan your Spotify top artists across your listening history, select 5 representative seed artists, and find similar hidden gems on Last.fm.
                        </p>
                      </div>
                    </div>
                  ) : (
                    <CustomArtistSelector
                      tokenRef={tokenRef}
                      selectedArtists={customArtists}
                      onAddArtist={handleAddCustomArtist}
                      onRemoveArtist={handleRemoveCustomArtist}
                    />
                  )}

                  {/* Curate Button */}
                  <div className="flex justify-center pt-4 border-t border-neutral-900/60">
                    <button
                      onClick={handleRetry}
                      disabled={cooldown > 0 || (mode === 'custom' && customArtists.length === 0)}
                      className={`px-8 py-3.5 rounded-full font-bold text-xs uppercase tracking-widest transition-all duration-300 transform hover:scale-[1.03] active:scale-[0.97] flex items-center justify-center gap-2 ${
                        cooldown > 0
                          ? "bg-neutral-800 border border-neutral-700 text-neutral-500 cursor-not-allowed select-none"
                          : mode === 'custom' && customArtists.length === 0
                          ? "bg-neutral-900 border border-neutral-850 text-neutral-500 cursor-not-allowed select-none"
                          : "bg-emerald-500 hover:bg-emerald-400 text-neutral-950 hover:shadow-lg hover:shadow-emerald-500/10 cursor-pointer"
                      }`}
                    >
                      {cooldown > 0
                        ? `Cooldown: ${Math.floor(cooldown / 60)}:${(cooldown % 60).toString().padStart(2, '0')}`
                        : mode === 'custom' && customArtists.length === 0
                        ? "Select Seeds to Begin"
                        : "Start Recommendation Analysis"}
                    </button>
                  </div>
                </div>
              )
            )}
          </div>

          {/* Sidebar Area: Instant Favorites (Right: 4 columns) */}
          <div className="lg:col-span-4 space-y-6 w-full">
            <InstantFavorites tracks={instantTracks} loading={instantLoading} />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-6 border-t border-neutral-900 text-center text-[10px] text-neutral-500 font-semibold tracking-wider uppercase">
        © 2026 fully client-side Spotify similarity engine • powered by Last.fm
      </footer>
    </div>
  );
}

export default App;
